export default {
  provinces: [
    {
      id: 1,
      state_id: 1,
      state_name: "Guatemala",
      name: "Guatemala",
    },
    {
      id: 2,
      state_id: 1,
      state_name: "Guatemala",
      name: "Santa Catarina Pinula",
    },
    {
      id: 3,
      state_id: 1,
      state_name: "Guatemala",
      name: "San José Pinula",
    },
    {
      id: 4,
      state_id: 1,
      state_name: "Guatemala",
      name: "San José del Golfo",
    },
    {
      id: 5,
      state_id: 1,
      state_name: "Guatemala",
      name: "Palencia",
    },
    {
      id: 6,
      state_id: 1,
      state_name: "Guatemala",
      name: "Chinautla",
    },
    {
      id: 7,
      state_id: 1,
      state_name: "Guatemala",
      name: "San Pedro Ayampuc",
    },
    {
      id: 8,
      state_id: 1,
      state_name: "Guatemala",
      name: "Mixco",
    },
    {
      id: 9,
      state_id: 1,
      state_name: "Guatemala",
      name: "San Pedro Sacatepéquez",
    },
    {
      id: 10,
      state_id: 1,
      state_name: "Guatemala",
      name: "San Juan Sacatepéquez",
    },
    {
      id: 11,
      state_id: 1,
      state_name: "Guatemala",
      name: "San Raymundo",
    },
    {
      id: 12,
      state_id: 1,
      state_name: "Guatemala",
      name: "Chuarrancho",
    },
    {
      id: 13,
      state_id: 1,
      state_name: "Guatemala",
      name: "Fraijanes",
    },
    {
      id: 14,
      state_id: 1,
      state_name: "Guatemala",
      name: "Amatitlán",
    },
    {
      id: 15,
      state_id: 1,
      state_name: "Guatemala",
      name: "Villa Nueva",
    },
    {
      id: 16,
      state_id: 1,
      state_name: "Guatemala",
      name: "Villa Canales",
    },
    {
      id: 17,
      state_id: 1,
      state_name: "Guatemala",
      name: "San Miguel Petapa",
    },
    {
      id: 18,
      state_id: 2,
      state_name: "El Progreso",
      name: "Guastatoya",
    },
    {
      id: 19,
      state_id: 2,
      state_name: "El Progreso",
      name: "El Jícaro",
    },
    {
      id: 20,
      state_id: 2,
      state_name: "El Progreso",
      name: "Morazán",
    },
    {
      id: 21,
      state_id: 2,
      state_name: "El Progreso",
      name: "San Agustín Acasaguastlán",
    },
    {
      id: 22,
      state_id: 2,
      state_name: "El Progreso",
      name: "San Antonio La Paz",
    },
    {
      id: 23,
      state_id: 2,
      state_name: "El Progreso",
      name: "San Cristóbal Acasaguastlán",
    },
    {
      id: 24,
      state_id: 2,
      state_name: "El Progreso",
      name: "Sanarate",
    },
    {
      id: 25,
      state_id: 2,
      state_name: "El Progreso",
      name: "Sansare",
    },
    {
      id: 26,
      state_id: 3,
      state_name: "Sacatepéquez",
      name: "Alotenango",
    },
    {
      id: 27,
      state_id: 3,
      state_name: "Sacatepéquez",
      name: "Ciudad Vieja",
    },
    {
      id: 28,
      state_id: 3,
      state_name: "Sacatepéquez",
      name: "Jocotenango",
    },
    {
      id: 29,
      state_id: 3,
      state_name: "Sacatepéquez",
      name: "Antigua Guatemala",
    },
    {
      id: 30,
      state_id: 3,
      state_name: "Sacatepéquez",
      name: "Magdalena Milpas Altas",
    },
    {
      id: 31,
      state_id: 3,
      state_name: "Sacatepéquez",
      name: "Pastores",
    },
    {
      id: 32,
      state_id: 3,
      state_name: "Sacatepéquez",
      name: "San Antonio Aguas Calientes",
    },
    {
      id: 33,
      state_id: 3,
      state_name: "Sacatepéquez",
      name: "San Bartolomé Milpas Altas",
    },
    {
      id: 34,
      state_id: 3,
      state_name: "Sacatepéquez",
      name: "San Lucas Sacatepéquez",
    },
    {
      id: 35,
      state_id: 3,
      state_name: "Sacatepéquez",
      name: "San Miguel Dueñas",
    },
    {
      id: 36,
      state_id: 3,
      state_name: "Sacatepéquez",
      name: "Santa Catarina Barahona",
    },
    {
      id: 37,
      state_id: 3,
      state_name: "Sacatepéquez",
      name: "Santa Lucía Milpas Altas",
    },
    {
      id: 38,
      state_id: 3,
      state_name: "Sacatepéquez",
      name: "Santa María de Jesús",
    },
    {
      id: 39,
      state_id: 3,
      state_name: "Sacatepéquez",
      name: "Santiago Sacatepéquez",
    },
    {
      id: 40,
      state_id: 3,
      state_name: "Sacatepéquez",
      name: "Santo Domingo Xenacoj",
    },
    {
      id: 41,
      state_id: 3,
      state_name: "spq",
      name: "Sumpango",
    },
    {
      id: 42,
      state_id: 4,
      state_name: "Chimaltemango",
      name: "Chimaltenango",
    },
    {
      id: 43,
      state_id: 4,
      state_name: "Chimaltemango",
      name: "San José Poaquíl",
    },
    {
      id: 44,
      state_id: 4,
      state_name: "Chimaltemango",
      name: "San Martín Jilotepeque",
    },
    {
      id: 45,
      state_id: 4,
      state_name: "Chimaltemango",
      name: "San Juan Comalapa",
    },
    {
      id: 46,
      state_id: 4,
      state_name: "Chimaltemango",
      name: "Santa Apolonia",
    },
    {
      id: 47,
      state_id: 4,
      state_name: "Chimaltemango",
      name: "Tecpán (Guatemala)",
    },
    {
      id: 48,
      state_id: 4,
      state_name: "Chimaltemango",
      name: "Patzún",
    },
    {
      id: 49,
      state_id: 4,
      state_name: "Chimaltemango",
      name: "San Miguel Pochuta",
    },
    {
      id: 50,
      state_id: 4,
      state_name: "Chimaltemango",
      name: "Patzicía",
    },
    {
      id: 51,
      state_id: 4,
      state_name: "Chimaltemango",
      name: "Santa Cruz Balanyá",
    },
    {
      id: 52,
      state_id: 4,
      state_name: "Chimaltemango",
      name: "Acatenango",
    },
    {
      id: 53,
      state_id: 4,
      state_name: "Chimaltemango",
      name: "San Pedro Yepocapa",
    },
    {
      id: 54,
      state_id: 4,
      state_name: "Chimaltemango",
      name: "San Andrés Itzapa",
    },
    {
      id: 55,
      state_id: 4,
      state_name: "Chimaltemango",
      name: "Parramos",
    },
    {
      id: 56,
      state_id: 4,
      state_name: "Chimaltemango",
      name: "Zaragoza",
    },
    {
      id: 57,
      state_id: 4,
      state_name: "Chimaltemango",
      name: "El Tejar",
    },
    {
      id: 58,
      state_id: 5,
      state_name: "Escuintla",
      name: "Escuintla",
    },
    {
      id: 59,
      state_id: 5,
      state_name: "Escuintla",
      name: "Guanagazapa",
    },
    {
      id: 60,
      state_id: 5,
      state_name: "Escuintla",
      name: "Iztapa",
    },
    {
      id: 61,
      state_id: 5,
      state_name: "Escuintla",
      name: "La Democracia",
    },
    {
      id: 62,
      state_id: 5,
      state_name: "Escuintla",
      name: "La Gomera",
    },
    {
      id: 63,
      state_id: 5,
      state_name: "Escuintla",
      name: "Masagua",
    },
    {
      id: 64,
      state_id: 5,
      state_name: "Escuintla",
      name: "Nueva Concepción",
    },
    {
      id: 65,
      state_id: 5,
      state_name: "Escuintla",
      name: "Palín",
    },
    {
      id: 66,
      state_id: 5,
      state_name: "Escuintla",
      name: "Puerto San José",
    },
    {
      id: 67,
      state_id: 5,
      state_name: "Escuintla",
      name: "San Vicente Pacaya",
    },
    {
      id: 68,
      state_id: 5,
      state_name: "Escuintla",
      name: "Santa Lucía Cotzumalguapa",
    },
    {
      id: 69,
      state_id: 5,
      state_name: "Escuintla",
      name: "Sipacate",
    },
    {
      id: 70,
      state_id: 5,
      state_name: "Escuintla",
      name: "Siquinalá",
    },
    {
      id: 71,
      state_id: 5,
      state_name: "Escuintla",
      name: "Pueblo Nuevo Tiquisate",
    },
    {
      id: 72,
      state_id: 6,
      state_name: "Santa Rosa",
      name: "Cuilapa",
    },
    {
      id: 73,
      state_id: 6,
      state_name: "Santa Rosa",
      name: "Barberena",
    },
    {
      id: 74,
      state_id: 6,
      state_name: "Santa Rosa",
      name: "Casillas",
    },
    {
      id: 75,
      state_id: 6,
      state_name: "Santa Rosa",
      name: "Chiquimulilla",
    },
    {
      id: 76,
      state_id: 6,
      state_name: "Santa Rosa",
      name: "Guazacapán",
    },
    {
      id: 77,
      state_id: 6,
      state_name: "Santa Rosa",
      name: "Nueva Santa Rosa",
    },
    {
      id: 78,
      state_id: 6,
      state_name: "Santa Rosa",
      name: "Oratorio",
    },
    {
      id: 79,
      state_id: 6,
      state_name: "Santa Rosa",
      name: "Pueblo Nuevo Viñas",
    },
    {
      id: 80,
      state_id: 6,
      state_name: "Santa Rosa",
      name: "San Juan Tecuaco",
    },
    {
      id: 81,
      state_id: 6,
      state_name: "Santa Rosa",
      name: "San Rafael Las Flores",
    },
    {
      id: 82,
      state_id: 6,
      state_name: "Santa Rosa",
      name: "Santa Cruz Naranjo",
    },
    {
      id: 83,
      state_id: 6,
      state_name: "Santa Rosa",
      name: "Santa María Ixhuatán",
    },
    {
      id: 84,
      state_id: 6,
      state_name: "Santa Rosa",
      name: "Santa Rosa de Lima",
    },
    {
      id: 85,
      state_id: 6,
      state_name: "Santa Rosa",
      name: "Taxisco",
    },
    {
      id: 86,
      state_id: 7,
      state_name: "Sololá",
      name: "Sololá",
    },
    {
      id: 87,
      state_id: 7,
      state_name: "Sololá",
      name: "Concepción",
    },
    {
      id: 88,
      state_id: 7,
      state_name: "Sololá",
      name: "Nahualá",
    },
    {
      id: 89,
      state_id: 7,
      state_name: "Sololá",
      name: "Panajachel",
    },
    {
      id: 90,
      state_id: 7,
      state_name: "Sololá",
      name: "San Andrés Semetabaj",
    },
    {
      id: 91,
      state_id: 7,
      state_name: "Sololá",
      name: "San Antonio Palopó",
    },
    {
      id: 92,
      state_id: 7,
      state_name: "Sololá",
      name: "San José Chacayá",
    },
    {
      id: 93,
      state_id: 7,
      state_name: "Sololá",
      name: "San Juan La Laguna",
    },
    {
      id: 94,
      state_id: 7,
      state_name: "Sololá",
      name: "San Lucas Tolimán",
    },
    {
      id: 95,
      state_id: 7,
      state_name: "Sololá",
      name: "San Marcos La Laguna",
    },
    {
      id: 96,
      state_id: 7,
      state_name: "Sololá",
      name: "San Pablo La Laguna",
    },
    {
      id: 97,
      state_id: 7,
      state_name: "Sololá",
      name: "San Pedro La Laguna",
    },
    {
      id: 98,
      state_id: 7,
      state_name: "Sololá",
      name: "Santa Catarina Ixtahuacán",
    },
    {
      id: 99,
      state_id: 7,
      state_name: "Sololá",
      name: "Santa Catarina Palopó",
    },
    {
      id: 100,
      state_id: 7,
      state_name: "Sololá",
      name: "Santa Clara La Laguna",
    },
    {
      id: 101,
      state_id: 7,
      state_name: "Sololá",
      name: "Santa Cruz La Laguna",
    },
    {
      id: 102,
      state_id: 7,
      state_name: "Sololá",
      name: "Santa Lucía Utatlán",
    },
    {
      id: 103,
      state_id: 7,
      state_name: "Sololá",
      name: "Santa María Visitación",
    },
    {
      id: 104,
      state_id: 7,
      state_name: "Sololá",
      name: "Santiago Atitlán",
    },
    {
      id: 105,
      state_id: 8,
      state_name: "Totonicapán",
      name: "Totonicapán",
    },
    {
      id: 106,
      state_id: 8,
      state_name: "Totonicapán",
      name: "San Cristóbal Totonicapán",
    },
    {
      id: 107,
      state_id: 8,
      state_name: "Totonicapán",
      name: "San Francisco El Alto",
    },
    {
      id: 108,
      state_id: 8,
      state_name: "Totonicapán",
      name: "San Andrés Xecul",
    },
    {
      id: 109,
      state_id: 8,
      state_name: "Totonicapán",
      name: "Momostenango",
    },
    {
      id: 110,
      state_id: 8,
      state_name: "Totonicapán",
      name: "Santa María Chiquimula",
    },
    {
      id: 111,
      state_id: 8,
      state_name: "Totonicapán",
      name: "Santa Lucía La Reforma",
    },
    {
      id: 112,
      state_id: 8,
      state_name: "Totonicapán",
      name: "San Bartolo",
    },
    {
      id: 113,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "Quetzaltenango",
    },
    {
      id: 114,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "Almolonga",
    },
    {
      id: 115,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "Cabricán",
    },
    {
      id: 116,
      state_id: 9,
      name: "Cajolá",
    },
    {
      id: 117,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "Cantel",
    },
    {
      id: 118,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "Coatepeque",
    },
    {
      id: 119,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "Colomba Costa Cuca",
    },
    {
      id: 120,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "Concepción Chiquirichapa",
    },
    {
      id: 121,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "El Palmar",
    },
    {
      id: 122,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "Flores Costa Cuca",
    },
    {
      id: 123,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "Génova",
    },
    {
      id: 124,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "Huitán",
    },
    {
      id: 125,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "La Esperanza",
    },
    {
      id: 126,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "Olintepeque",
    },
    {
      id: 127,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "Palestina de los Altos",
    },
    {
      id: 128,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "Salcajá",
    },
    {
      id: 129,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "San Carlos Sija",
    },
    {
      id: 130,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "San Francisco La Unión",
    },
    {
      id: 131,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "San Juan Ostuncalco",
    },
    {
      id: 132,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "San Martín Sacatepequez",
    },
    {
      id: 133,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "San Mateo",
    },
    {
      id: 134,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "San Miguel Sigüilá",
    },
    {
      id: 135,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "Sibilia",
    },
    {
      id: 136,
      state_id: 9,
      state_name: "Quetzaltenango",
      name: "Zunil",
    },
    {
      id: 137,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "Mazatenango",
    },
    {
      id: 138,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "Chicacao",
    },
    {
      id: 139,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "Cuyotenango",
    },
    {
      id: 140,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "Patulul",
    },
    {
      id: 141,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "Pueblo Nuevo",
    },
    {
      id: 142,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "Río Bravo",
    },
    {
      id: 143,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "Samayac",
    },
    {
      id: 144,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "San Antonio Suchitepéquez",
    },
    {
      id: 145,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "San Bernardino",
    },
    {
      id: 146,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "San Francisco Zapotitlán",
    },
    {
      id: 147,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "San Gabriel",
    },
    {
      id: 148,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "San José El Ídolo",
    },
    {
      id: 149,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "San José La Máquina",
    },
    {
      id: 150,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "San Juan Bautista",
    },
    {
      id: 151,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "San Lorenzo",
    },
    {
      id: 152,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "San Miguel Panán",
    },
    {
      id: 153,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "San Pablo Jocopilas",
    },
    {
      id: 154,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "Santa Bárbara",
    },
    {
      id: 155,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "Santo Domingo Suchitepéquez",
    },
    {
      id: 156,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "Santo Tomás La Unión",
    },
    {
      id: 157,
      state_id: 10,
      state_name: "Suchitepéquez",
      name: "Zunilito",
    },
    {
      id: 158,
      state_id: 11,
      state_name: "Retalhuleu",
      name: "Retalhuleu",
    },
    {
      id: 159,
      state_id: 11,
      state_name: "Retalhuleu",
      name: "Champerico",
    },
    {
      id: 160,
      state_id: 11,
      state_name: "Retalhuleu",
      name: "El Asintal",
    },
    {
      id: 161,
      state_id: 11,
      state_name: "Retalhuleu",
      name: "Nuevo San Carlos",
    },
    {
      id: 162,
      state_id: 11,
      state_name: "Retalhuleu",
      name: "San Andrés Villa Seca",
    },
    {
      id: 163,
      state_id: 11,
      state_name: "Retalhuleu",
      name: "San Felipe",
    },
    {
      id: 164,
      state_id: 11,
      state_name: "Retalhuleu",
      name: "San Martín Zapotitlán",
    },
    {
      id: 165,
      state_id: 11,
      state_name: "Retalhuleu",
      name: "San Sebastián",
    },
    {
      id: 166,
      state_id: 11,
      state_name: "Retalhuleu",
      name: "Santa Cruz Muluá",
    },
    {
      id: 167,
      state_id: 12,
      state_name: "San Marcos",
      name: "San Marcos",
    },
    {
      id: 168,
      state_id: 12,
      state_name: "San Marcos",
      name: "Ayutla",
    },
    {
      id: 169,
      state_id: 12,
      state_name: "San Marcos",
      name: "Catarina",
    },
    {
      id: 170,
      state_id: 12,
      state_name: "San Marcos",
      name: "Comitancillo",
    },
    {
      id: 171,
      state_id: 12,
      state_name: "San Marcos",
      name: "Concepción Tutuapa",
    },
    {
      id: 172,
      state_id: 12,
      state_name: "San Marcos",
      name: "El Quetzal",
    },
    {
      id: 173,
      state_id: 12,
      state_name: "San Marcos",
      name: "El Tumbador",
    },
    {
      id: 174,
      state_id: 12,
      state_name: "San Marcos",
      name: "Esquipulas Palo Gordo",
    },
    {
      id: 175,
      state_id: 12,
      state_name: "San Marcos",
      name: "Ixchiguán",
    },
    {
      id: 176,
      state_id: 12,
      state_name: "San Marcos",
      name: "La Blanca",
    },
    {
      id: 177,
      state_id: 12,
      state_name: "San Marcos",
      name: "La Reforma",
    },
    {
      id: 178,
      state_id: 12,
      state_name: "San Marcos",
      name: "Malacatán",
    },
    {
      id: 179,
      state_id: 12,
      state_name: "San Marcos",
      name: "Nuevo Progreso",
    },
    {
      id: 180,
      state_id: 12,
      state_name: "San Marcos",
      name: "Ocós",
    },
    {
      id: 181,
      state_id: 12,
      state_name: "San Marcos",
      name: "Pajapita",
    },
    {
      id: 182,
      state_id: 12,
      state_name: "San Marcos",
      name: "Río Blanco",
    },
    {
      id: 183,
      state_id: 12,
      state_name: "San Marcos",
      name: "San Antonio Sacatepéquez",
    },
    {
      id: 184,
      state_id: 12,
      state_name: "San Marcos",
      name: "San Cristóbal Cucho",
    },
    {
      id: 185,
      state_id: 12,
      state_name: "San Marcos",
      name: "San José El Rodeo",
    },
    {
      id: 186,
      state_id: 12,
      state_name: "San Marcos",
      name: "San José Ojetenam",
    },
    {
      id: 187,
      state_id: 12,
      state_name: "San Marcos",
      name: "San Lorenzo",
    },
    {
      id: 188,
      state_id: 12,
      state_name: "San Marcos",
      name: "San Miguel Ixtahuacán",
    },
    {
      id: 189,
      state_id: 12,
      state_name: "San Marcos",
      name: "San Pablo",
    },
    {
      id: 190,
      state_id: 12,
      state_name: "San Marcos",
      name: "San Pedro Sacatepéquez",
    },
    {
      id: 191,
      state_id: 12,
      state_name: "San Marcos",
      name: "San Rafael Pie de la Cuesta",
    },
    {
      id: 192,
      state_id: 12,
      state_name: "San Marcos",
      name: "Sibinal",
    },
    {
      id: 193,
      state_id: 12,
      state_name: "San Marcos",
      name: "Sipacapa",
    },
    {
      id: 194,
      state_id: 12,
      state_name: "San Marcos",
      name: "Tacaná",
    },
    {
      id: 195,
      state_id: 12,
      state_name: "San Marcos",
      name: "Tajumulco",
    },
    {
      id: 196,
      state_id: 12,
      state_name: "San Marcos",
      name: "Tejutla",
    },
    {
      id: 197,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Huehuetenango",
    },
    {
      id: 198,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Aguacatán",
    },
    {
      id: 199,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Chiantla",
    },
    {
      id: 200,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Colotenango",
    },
    {
      id: 201,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Concepción Huista",
    },
    {
      id: 202,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Cuilco",
    },
    {
      id: 203,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Jacaltenango",
    },
    {
      id: 204,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "La Libertad",
    },
    {
      id: 205,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "La Democracia",
    },
    {
      id: 206,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Malacatancito",
    },
    {
      id: 207,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Nentón",
    },
    {
      id: 208,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Petatán",
    },
    {
      id: 209,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "San Antonio Huista",
    },
    {
      id: 210,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "San Gaspar Ixchil",
    },
    {
      id: 211,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "San Ildefonso Ixtahuacán",
    },
    {
      id: 212,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "San Juan Atitán",
    },
    {
      id: 213,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "San Juan Ixcoy",
    },
    {
      id: 214,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "San Mateo Ixtatán",
    },
    {
      id: 215,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "San Miguel Acatán",
    },
    {
      id: 216,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "San Pedro Nécta",
    },
    {
      id: 217,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "San Pedro Soloma",
    },
    {
      id: 218,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "San Rafael La Independencia",
    },
    {
      id: 219,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "San Rafael Pétzal",
    },
    {
      id: 220,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "San Sebastián Coatán",
    },
    {
      id: 221,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "San Sebastián Huehuetenango",
    },
    {
      id: 222,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Santa Ana Huista",
    },
    {
      id: 223,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Santa Bárbara",
    },
    {
      id: 224,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Santa Cruz Barillas",
    },
    {
      id: 225,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Santa Eulalia",
    },
    {
      id: 226,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Santiago Chimaltenango",
    },
    {
      id: 227,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Tectitán",
    },
    {
      id: 228,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Todos Santos Cuchumatán",
    },
    {
      id: 229,
      state_id: 13,
      state_name: "Huehuetenango",
      name: "Unión Cantinil",
    },
    {
      id: 230,
      state_id: 14,
      state_name: "Quiché",
      name: "Santa Cruz del Quiché",
    },
    {
      id: 231,
      state_id: 14,
      state_name: "Quiché",
      name: "Canillá",
    },
    {
      id: 232,
      state_id: 14,
      state_name: "Quiché",
      name: "Chajul",
    },
    {
      id: 233,
      state_id: 14,
      state_name: "Quiché",
      name: "Chicamán",
    },
    {
      id: 234,
      state_id: 14,
      state_name: "Quiché",
      name: "Chiché",
    },
    {
      id: 235,
      state_id: 14,
      state_name: "Quiché",
      name: "Chichicastenango",
    },
    {
      id: 236,
      state_id: 14,
      state_name: "Quiché",
      name: "Chinique",
    },
    {
      id: 237,
      state_id: 14,
      state_name: "Quiché",
      name: "Cunén",
    },
    {
      id: 238,
      state_id: 14,
      state_name: "Quiché",
      name: "Ixcán",
    },
    {
      id: 239,
      state_id: 14,
      state_name: "Quiché",
      name: "Joyabaj",
    },
    {
      id: 240,
      state_id: 14,
      state_name: "Quiché",
      name: "Pachalum",
    },
    {
      id: 241,
      state_id: 14,
      state_name: "Quiché",
      name: "Patzité",
    },
    {
      id: 242,
      state_id: 14,
      state_name: "Quiché",
      name: "Sacapulas",
    },
    {
      id: 243,
      state_id: 14,
      state_name: "Quiché",
      name: "San Andrés Sajcabajá",
    },
    {
      id: 244,
      state_id: 14,
      state_name: "Quiché",
      name: "San Antonio Ilotenango",
    },
    {
      id: 245,
      state_id: 14,
      state_name: "Quiché",
      name: "San Bartolomé Jocotenango",
    },
    {
      id: 246,
      state_id: 14,
      state_name: "Quiché",
      name: "San Juan Cotzal",
    },
    {
      id: 247,
      state_id: 14,
      state_name: "Quiché",
      name: "San Pedro Jocopilas",
    },
    {
      id: 248,
      state_id: 14,
      state_name: "Quiché",
      name: "Santa María Nebaj",
    },
    {
      id: 249,
      state_id: 14,
      state_name: "Quiché",
      name: "Uspantán",
    },
    {
      id: 250,
      state_id: 14,
      state_name: "Quiché",
      name: "Zacualpa",
    },
    {
      id: 251,
      state_id: 15,
      name: "Salamá",
    },
    {
      id: 252,
      state_id: 15,
      state_name: "Baja Verapaz",
      name: "San Miguel Chicaj",
    },
    {
      id: 253,
      state_id: 15,
      state_name: "Baja Verapaz",
      name: "Rabinal",
    },
    {
      id: 254,
      state_id: 15,
      state_name: "Baja Verapaz",
      name: "Cubulco",
    },
    {
      id: 255,
      state_id: 15,
      state_name: "Baja Verapaz",
      name: "Granados",
    },
    {
      id: 256,
      state_id: 15,
      state_name: "Baja Verapaz",
      name: "Santa Cruz el Chol",
    },
    {
      id: 257,
      state_id: 15,
      state_name: "Baja Verapaz",
      name: "San Jerónimo",
    },
    {
      id: 258,
      state_id: 15,
      state_name: "Baja Verapaz",
      name: "Purulhá",
    },
    {
      id: 259,
      state_id: 16,
      state_name: "Alta Verapaz",
      name: "Cobán",
    },
    {
      id: 260,
      state_id: 16,
      state_name: "Alta Verapaz",
      name: "Chahal",
    },
    {
      id: 261,
      state_id: 16,
      state_name: "Alta Verapaz",
      name: "Chisec",
    },
    {
      id: 262,
      state_id: 16,
      state_name: "Alta Verapaz",
      name: "Fray Bartolomé de las Casas",
    },
    {
      id: 263,
      state_id: 16,
      state_name: "Alta Verapaz",
      name: "Lanquín",
    },
    {
      id: 264,
      state_id: 16,
      state_name: "Alta Verapaz",
      name: "Panzós",
    },
    {
      id: 265,
      state_id: 16,
      state_name: "Alta Verapaz",
      name: "Raxruhá",
    },
    {
      id: 266,
      state_id: 16,
      state_name: "Alta Verapaz",
      name: "San Cristóbal Verapaz",
    },
    {
      id: 267,
      state_id: 16,
      state_name: "Alta Verapaz",
      name: "San Juan Chamelco",
    },
    {
      id: 268,
      state_id: 16,
      state_name: "Alta Verapaz",
      name: "San Miguel Tucurú",
    },
    {
      id: 269,
      state_id: 16,
      state_name: "Alta Verapaz",
      name: "San Pedro Carchá",
    },
    {
      id: 270,
      state_id: 16,
      state_name: "Alta Verapaz",
      name: "Santa Catalina La Tinta",
    },
    {
      id: 271,
      state_id: 16,
      state_name: "Alta Verapaz",
      name: "Santa Cruz Verapaz",
    },
    {
      id: 272,
      state_id: 16,
      state_name: "Alta Verapaz",
      name: "Santa María Cahabón",
    },
    {
      id: 273,
      state_id: 16,
      state_name: "Alta Verapaz",
      name: "Senahú",
    },
    {
      id: 274,
      state_id: 16,
      state_name: "Alta Verapaz",
      name: "Tactíc",
    },
    {
      id: 275,
      state_id: 16,
      state_name: "Alta Verapaz",
      name: "Tamahú",
    },
    {
      id: 276,
      state_id: 17,
      state_name: "Petén",
      name: "Flores",
    },
    {
      id: 277,
      state_id: 17,
      state_name: "Petén",
      name: "Dolores",
    },
    {
      id: 278,
      state_id: 17,
      state_name: "Petén",
      name: "El Chal",
    },
    {
      id: 279,
      state_id: 17,
      state_name: "Petén",
      name: "La Libertad",
    },
    {
      id: 280,
      state_id: 17,
      state_name: "Petén",
      name: "Las Cruces",
    },
    {
      id: 281,
      state_id: 17,
      state_name: "Petén",
      name: "Melchor de Mencos",
    },
    {
      id: 282,
      state_id: 17,
      state_name: "Petén",
      name: "Poptún",
    },
    {
      id: 283,
      state_id: 17,
      state_name: "Petén",
      name: "San Andrés",
    },
    {
      id: 284,
      state_id: 17,
      state_name: "Petén",
      name: "San Benito",
    },
    {
      id: 285,
      state_id: 17,
      state_name: "Petén",
      name: "San Francisco",
    },
    {
      id: 286,
      state_id: 17,
      state_name: "Petén",
      name: "San José",
    },
    {
      id: 287,
      state_id: 17,
      state_name: "Petén",
      name: "San Luis",
    },
    {
      id: 288,
      state_id: 17,
      state_name: "Petén",
      name: "Santa Ana",
    },
    {
      id: 289,
      state_id: 17,
      state_name: "Petén",
      name: "Sayaxché",
    },
    {
      id: 290,
      state_id: 18,
      state_name: "Izabal",
      name: "Puerto Barrios",
    },
    {
      id: 291,
      state_id: 18,
      state_name: "Izabal",
      name: "El Estor",
    },
    {
      id: 292,
      state_id: 18,
      state_name: "Izabal",
      name: "Livingston",
    },
    {
      id: 293,
      state_id: 18,
      state_name: "Izabal",
      name: "Los Amates",
    },
    {
      id: 294,
      state_id: 18,
      state_name: "Izabal",
      name: "Morales",
    },
    {
      id: 295,
      state_id: 19,
      state_name: "Zacapa",
      name: "Zacapa",
    },
    {
      id: 296,
      state_id: 19,
      state_name: "Zacapa",
      name: "Cabañas",
    },
    {
      id: 297,
      state_id: 19,
      state_name: "Zacapa",
      name: "Estanzuela",
    },
    {
      id: 298,
      state_id: 19,
      state_name: "Zacapa",
      name: "Gualán",
    },
    {
      id: 299,
      state_id: 19,
      state_name: "Zacapa",
      name: "Huité",
    },
    {
      id: 300,
      state_id: 19,
      state_name: "Zacapa",
      name: "La Unión",
    },
    {
      id: 301,
      state_id: 19,
      state_name: "Zacapa",
      name: "Río Hondo",
    },
    {
      id: 302,
      state_id: 19,
      state_name: "Zacapa",
      name: "San Diego",
    },
    {
      id: 303,
      state_id: 19,
      state_name: "Zacapa",
      name: "San Jorge",
    },
    {
      id: 304,
      state_id: 19,
      state_name: "Zacapa",
      name: "Teculután",
    },
    {
      id: 305,
      state_id: 19,
      state_name: "Zacapa",
      name: "Usumatlán",
    },
    {
      id: 306,
      state_id: 20,
      state_name: "Chiquimula",
      name: "Chiquimula",
    },
    {
      id: 307,
      state_id: 20,
      state_name: "chiq",
      name: "Camotán",
    },
    {
      id: 308,
      state_id: 20,
      state_name: "Chiquimula",
      name: "Concepción Las Minas",
    },
    {
      id: 309,
      state_id: 20,
      state_name: "Chiquimula",
      name: "Esquipulas",
    },
    {
      id: 310,
      state_id: 20,
      state_name: "Chiquimula",
      name: "Ipala",
    },
    {
      id: 311,
      state_id: 20,
      state_name: "Chiquimula",
      name: "Jocotán",
    },
    {
      id: 312,
      state_id: 20,
      state_name: "Chiquimula",
      name: "Olopa",
    },
    {
      id: 313,
      state_id: 20,
      state_name: "Chiquimula",
      name: "Quezaltepeque",
    },
    {
      id: 314,
      state_id: 20,
      state_name: "Chiquimula",
      name: "San Jacinto",
    },
    {
      id: 315,
      state_id: 20,
      state_name: "Chiquimula",
      name: "San José La Arada",
    },
    {
      id: 316,
      state_id: 20,
      state_name: "Chiquimula",
      name: "San Juan Ermita",
    },
    {
      id: 317,
      state_id: 21,
      state_name: "Jalapa",
      name: "Jalapa",
    },
    {
      id: 318,
      state_id: 21,
      state_name: "Jalapa",
      name: "Mataquescuintla",
    },
    {
      id: 319,
      state_id: 21,
      state_name: "Jalapa",
      name: "Monjas",
    },
    {
      id: 320,
      state_id: 21,
      state_name: "Jalapa",
      name: "San Carlos Alzatate",
    },
    {
      id: 321,
      state_id: 21,
      state_name: "Jalapa",
      name: "San Luis Jilotepeque",
    },
    {
      id: 322,
      state_id: 21,
      state_name: "Jalapa",
      name: "San Manuel Chaparrón",
    },
    {
      id: 323,
      state_id: 21,
      state_name: "Jalapa",
      name: "San Pedro Pinula",
    },
    {
      id: 324,
      state_id: 22,
      state_name: "Jutiapa",
      name: "Jutiapa",
    },
    {
      id: 325,
      state_id: 22,
      state_name: "Jutiapa",
      name: "Agua Blanca",
    },
    {
      id: 326,
      state_id: 22,
      state_name: "Jutiapa",
      name: "Asunción Mita",
    },
    {
      id: 327,
      state_id: 22,
      state_name: "Jutiapa",
      name: "Atescatempa",
    },
    {
      id: 328,
      state_id: 22,
      state_name: "Jutiapa",
      name: "Comapa",
    },
    {
      id: 329,
      state_id: 22,
      state_name: "Jutiapa",
      name: "Conguaco",
    },
    {
      id: 330,
      state_id: 22,
      state_name: "Jutiapa",
      name: "El Adelanto",
    },
    {
      id: 331,
      state_id: 22,
      state_name: "Jutiapa",
      name: "El Progreso",
    },
    {
      id: 332,
      state_id: 22,
      state_name: "Jutiapa",
      name: "Jalpatagua",
    },
    {
      id: 333,
      state_id: 22,
      state_name: "Jutiapa",
      name: "Jerez",
    },
    {
      id: 334,
      state_id: 22,
      state_name: "Jutiapa",
      name: "Moyuta",
    },
    {
      id: 335,
      state_id: 22,
      state_name: "Jutiapa",
      name: "Pasaco",
    },
    {
      id: 336,
      state_id: 22,
      state_name: "Jutiapa",
      name: "Quesada",
    },
    {
      id: 337,
      state_id: 22,
      state_name: "Jutiapa",
      name: "San José Acatempa",
    },
    {
      id: 338,
      state_id: 22,
      state_name: "Jutiapa",
      name: "Santa Catarina Mita",
    },
    {
      id: 339,
      state_id: 22,
      state_name: "Jutiapa",
      name: "Yupiltepeque",
    },
    {
      id: 340,
      state_id: 22,
      state_name: "Jutiapa",
      name: "Zapotitlán",
    },
  ],
};
