export default {
    provincesh: [
      {
        id: 1,
        state_id: 1,
        state_name: "Atlántida",
        name: "La Ceiba",
      },
      {
        id: 2,
        state_id: 1,
        state_name: "Atlántida",
        name: "Tela",
      },
      {
        id: 3,
        state_id: 1,
        state_name: "Atlántida",
        name: "Jutiapa",
      },
      {
        id: 4,
        state_id: 1,
        state_name: "Atlántida",
        name: "La Masica",
      },
      {
        id: 5,
        state_id: 1,
        state_name: "Atlántida",
        name: "San Francisco",
      },
      {
        id: 6,
        state_id: 1,
        state_name: "Atlántida",
        name: "Arizona",
      },
      {
        id: 7,
        state_id: 1,
        state_name: "Atlántida",
        name: "Esparta",
      },
      {
        id: 8,
        state_id: 1,
        state_name: "Atlántida",
        name: "El Porvenir",
      },

      {
        id: 9,
        state_id: 2,
        state_name: "Colón",
        name: "Trujillo",
      },
      {
        id: 10,
        state_id: 2,
        state_name: "Colón",
        name: "Balfate",
      },
      {
        id: 11,
        state_id: 2,
        state_name: "Colón",
        name: "Iriona",
      },
      {
        id: 12,
        state_id: 2,
        state_name: "Colón",
        name: "Limón",
      },
      {
        id: 13,
        state_id: 2,
        state_name: "Colón",
        name: "Sabá",
      },
      {
        id: 14,
        state_id: 2,
        state_name: "Colón",
        name: "Santa Fe",
      },
      {
        id: 15,
        state_id: 2,
        state_name: "Colón",
        name: "Santa Rosa de Aguán",
      },
      {
        id: 16,
        state_id: 2,
        state_name: "Colón",
        name: "Sonaguera",
      },
      {
        id: 17,
        state_id: 2,
        state_name: "Colón",
        name: "Tocoa",
      },
      {
        id: 18,
        state_id: 2,
        state_name: "Colón",
        name: "Bonito Oriental",
      },


      {
        id: 19,
        state_id: 3,
        state_name: "Comayagua",
        name: "Comayagua",
      },
      {
        id: 20,
        state_id: 3,
        state_name: "Comayagua",
        name: "Ajuterique",
      },
      {
        id: 21,
        state_id: 3,
        state_name: "Comayagua",
        name: "El Rosario",
      },
      {
        id: 22,
        state_id: 3,
        state_name: "Comayagua",
        name: "Esquías",
      },
      {
        id: 23,
        state_id: 3,
        state_name: "Comayagua",
        name: "Humuya",
      },
      {
        id: 24,
        state_id: 3,
        state_name: "Comayagua",
        name: "La libertad",
      },
      {
        id: 25,
        state_id: 3,
        state_name: "Comayagua",
        name: "Lamaní",
      },
      {
        id: 26,
        state_id: 3,
        state_name: "Comayagua",
        name: "La Trinidad",
      },
      {
        id: 27,
        state_id: 3,
        state_name: "Comayagua",
        name: "Lejamani",
      },
      {
        id: 28,
        state_id: 3,
        state_name: "Comayagua",
        name: "Meambar",
      },
      {
        id: 29,
        state_id: 3,
        state_name: "Comayagua",
        name: "Minas de Oro",
      },
      {
        id: 30,
        state_id: 3,
        state_name: "Comayagua",
        name: "Ojos de Agua",
      },
      {
        id: 31,
        state_id: 3,
        state_name: "Comayagua",
        name: "San Jerónimo (Honduras)",
      },
      {
        id: 32,
        state_id: 3,
        state_name: "Comayagua",
        name: "San José de Comayagua",
      },
      {
        id: 33,
        state_id: 3,
        state_name: "Comayagua",
        name: "San José del Potrero",
      },
      {
        id: 34,
        state_id: 3,
        state_name: "Comayagua",
        name: "San Luis",
      },
      {
        id: 35,
        state_id: 3,
        state_name: "Comayagua",
        name: "San Sebastián",
      },
      {
        id: 36,
        state_id: 3,
        state_name: "Comayagua",
        name: "Siguatepeque",
      },
      {
        id: 37,
        state_id: 3,
        state_name: "Comayagua",
        name: "Villa de San Antonio",
      },
      {
        id: 38,
        state_id: 3,
        state_name: "Comayagua",
        name: "Las Lajas",
      },
      {
        id: 39,
        state_id: 3,
        state_name: "Comayagua",
        name: "Taulabé",
      },

      {
        id: 40,
        state_id: 4,
        state_name: "Copán",
        name: "Santa Rosa de Copán",
      },

      {
        id: 41,
        state_id: 4,
        state_name: "Copán",
        name: "Cabañas",
      },
      {
        id: 42,
        state_id: 4,
        state_name: "Copán",
        name: "Concepción",
      },
      {
        id: 43,
        state_id: 4,
        state_name: "Copán",
        name: "Copán Ruinas",
      },
      {
        id: 44,
        state_id: 4,
        state_name: "Copán",
        name: "Corquín",
      },
      {
        id: 45,
        state_id: 4,
        state_name: "Copán",
        name: "Cucuyagua",
      },
      {
        id: 46,
        state_id: 4,
        state_name: "Copán",
        name: "Dolores",
      },
      {
        id: 47,
        state_id: 4,
        state_name: "Copán",
        name: "Dulce Nombre",
      },
      {
        id: 48,
        state_id: 4,
        state_name: "Copán",
        name: "El Paraíso",
      },
      {
        id: 49,
        state_id: 4,
        state_name: "Copán",
        name: "Florida",
      },
      {
        id: 50,
        state_id: 4,
        state_name: "Copán",
        name: "La Jigua",
      },
      {
        id: 51,
        state_id: 4,
        state_name: "Copán",
        name: "La Unión",
      },
      {
        id: 52,
        state_id: 4,
        state_name: "Copán",
        name: "Nueva Arcadia",
      },
      {
        id: 53,
        state_id: 4,
        state_name: "Copán",
        name: "San Agustín",
      },
      {
        id: 54,
        state_id: 4,
        state_name: "Copán",
        name: "San Antonio",
      },
      {
        id: 55,
        state_id: 4,
        state_name: "Copán",
        name: "San Jerónimo",
      },
      {
        id: 56,
        state_id: 4,
        state_name: "Copán",
        name: "San José",
      },
      {
        id: 57,
        state_id: 4,
        state_name: "Copán",
        name: "San Juan de Opoa",
      },
      {
        id: 58,
        state_id: 4,
        state_name: "Copán",
        name: "San Nicolás",
      },
      {
        id: 59,
        state_id: 4,
        state_name: "Copán",
        name: "San Pedro",
      },
      {
        id: 60,
        state_id: 4,
        state_name: "Copán",
        name: "Santa Rita",
      },
      {
        id: 61,
        state_id: 4,
        state_name: "Copán",
        name: "Trinidad de Copán",
      },
      {
        id: 62,
        state_id: 4,
        state_name: "Copán",
        name: "Veracruz",
      },

      {
        id: 63,
        state_id: 5,
        state_name: "Cortés",
        name: "San Pedro Sula",
      },
      {
        id: 64,
        state_id: 5,
        state_name: "Cortés",
        name: "Choloma",
      },
      {
        id: 65,
        state_id: 5,
        state_name: "Cortés",
        name: "Omoa",
      },
      {
        id: 66,
        state_id: 5,
        state_name: "Cortés",
        name: "Pimienta",
      },
      {
        id: 67,
        state_id: 5,
        state_name: "Cortés",
        name: "Potrerillos",
      },
      {
        id: 68,
        state_id: 5,
        state_name: "Cortés",
        name: "Puerto Cortés",
      },
      {
        id: 69,
        state_id: 5,
        state_name: "Cortés",
        name: "San Antonio de Cortés",
      },
      {
        id: 70,
        state_id: 5,
        state_name: "Cortés",
        name: "San Francisco de Yojoa",
      },
      {
        id: 71,
        state_id: 5,
        state_name: "Cortés",
        name: "San Manuel",
      },
      {
        id: 72,
        state_id: 5,
        state_name: "Cortés",
        name: "Santa Cruz de Yojoa",
      },
      {
        id: 73,
        state_id: 5,
        state_name: "Cortés",
        name: "Villanueva",
      },
      {
        id: 74,
        state_id: 5,
        state_name: "Cortés",
        name: "La Lima",
      },

      {
        id: 75,
        state_id: 6,
        state_name: "Choluteca",
        name: "Choluteca",
      },
      {
        id: 76,
        state_id: 6,
        state_name: "Choluteca",
        name: "Apacilagua",
      },
      {
        id: 77,
        state_id: 6,
        state_name: "Choluteca",
        name: "Concepción de María",
      },
      {
        id: 78,
        state_id: 6,
        state_name: "Choluteca",
        name: "Duyure",
      },
      {
        id: 79,
        state_id: 6,
        state_name: "Choluteca",
        name: "El Corpus",
      },
      {
        id: 80,
        state_id: 6,
        state_name: "Choluteca",
        name: "El Triunfo",
      },
      {
        id: 81,
        state_id: 6,
        state_name: "Choluteca",
        name: "Marcovia",
      },
      {
        id: 82,
        state_id: 6,
        state_name: "Choluteca",
        name: "Morolica",
      },
      {
        id: 83,
        state_id: 6,
        state_name: "Choluteca",
        name: "Namasigue",
      },
      {
        id: 84,
        state_id: 6,
        state_name: "Choluteca",
        name: "Orocuina",
      },
      {
        id: 85,
        state_id: 6,
        state_name: "Choluteca",
        name: "Pespire",
      },
      {
        id: 86,
        state_id: 6,
        state_name: "Choluteca",
        name: "San Antonio de Flores",
      },
      {
        id: 87,
        state_id: 6,
        state_name: "Choluteca",
        name: "San Isidro",
      },
      {
        id: 88,
        state_id: 6,
        state_name: "Choluteca",
        name: "San José",
      },
      {
        id: 89,
        state_id: 6,
        state_name: "Choluteca",
        name: "San Marcos de Colón",
      },
      {
        id: 90,
        state_id: 6,
        state_name: "Choluteca",
        name: "Santa Ana de Yusguare",
      },


      {
        id: 91,
        state_id: 7,
        state_name: "El Paraíso",
        name: "Yuscarán",
      },
      
    /*  {
        id: 92,
        state_id: 7,
        state_name: "El Paraíso",
        name: "San José Chacayá",
      },*/

      {
        id: 93,
        state_id: 7,
        state_name: "El Paraíso",
        name: "Alauca",
      },
      {
        id: 94,
        state_id: 7,
        state_name: "El Paraíso",
        name: "Danlí",
      },
      {
        id: 95,
        state_id: 7,
        state_name: "El Paraíso",
        name: "El Paraíso",
      },
      {
        id: 96,
        state_id: 7,
        state_name: "El Paraíso",
        name: "Güinope",
      },
      {
        id: 97,
        state_id: 7,
        state_name: "El Paraíso",
        name: "Jacaleapa",
      },
      {
        id: 98,
        state_id: 7,
        state_name: "El Paraíso",
        name: "Liure",
      },
      {
        id: 99,
        state_id: 7,
        state_name: "El Paraíso",
        name: "Morocelí",
      },
      {
        id: 100,
        state_id: 7,
        state_name: "El Paraíso",
        name: "Oropolí",
      },
      {
        id: 101,
        state_id: 7,
        state_name: "El Paraíso",
        name: "Potrerillos",
      },
      {
        id: 102,
        state_id: 7,
        state_name: "El Paraíso",
        name: "San Antonio de Flores",
      },
      {
        id: 103,
        state_id: 7,
        state_name: "El Paraíso",
        name: "San Lucas",
      },
      {
        id: 104,
        state_id: 7,
        state_name: "El Paraíso",
        name: "San Matías",
      },
      {
        id: 105,
        state_id: 7,
        state_name: "El Paraíso",
        name: "Soledad",
      },
      {
        id: 106,
        state_id: 7,
        state_name: "El Paraíso",
        name: "Teupasenti",
      },
      {
        id: 107,
        state_id: 7,
        state_name: "El Paraíso",
        name: "Texiguat",
      },
      {
        id: 108,
        state_id: 7,
        state_name: "El Paraíso",
        name: "Vado Ancho",
      },
      {
        id: 109,
        state_id: 7,
        state_name: "El Paraíso",
        name: "Yauyupe",
      },
      {
        id: 110,
        state_id: 7,
        state_name: "El Paraíso",
        name: "Trojes",
      },

 /*     {
        id: 111,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Santa Lucía La Reforma",
      },*/

      {
        id: 112,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Distrito Central",
      },
      {
        id: 113,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Alubarén",
      },
      {
        id: 114,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Cedros",
      },
      {
        id: 115,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Curarén",
      },
      {
        id: 116,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "El Porvenir",
      },
      {
        id: 117,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Guaimaca",
      },
      {
        id: 118,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "La Libertad",
      },
      {
        id: 119,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "La Venta",
      },
      {
        id: 120,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Lepaterique",
      },
      {
        id: 121,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Maraita",
      },
      {
        id: 122,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Marale",
      },
      {
        id: 123,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Nueva Armenia",
      },
      {
        id: 124,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Ojojona",
      },
      {
        id: 125,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Orica",
      },
      {
        id: 126,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Reitoca",
      },
      {
        id: 127,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Sabanagrande",
      },
      {
        id: 128,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "San Antonio de Oriente",
      },
      {
        id: 129,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "San Buenaventura",
      },
      {
        id: 130,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "San Ignacio",
      },
      {
        id: 131,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "San Juan de Flores",
      },
      {
        id: 132,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "San Miguelito",
      },
      {
        id: 133,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Santa Ana",
      },
      {
        id: 134,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Santa Lucía",
      },
      {
        id: 135,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Talanga",
      },
      {
        id: 136,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Tatumbla",
      },
      {
        id: 137,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Valle de Ángeles",
      },
      {
        id: 138,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Villa de San Francisco",
      },
      {
        id: 139,
        state_id: 8,
        state_name: "Francisco Morazán",
        name: "Vallecillo",
      },

      {
        id: 140,
        state_id: 9,
        state_name: "Gracias a Dios",
        name: "Puerto Lempira",
      },
      {
        id: 141,
        state_id: 9,
        state_name: "Gracias a Dios",
        name: "Brus Laguna",
      },
      {
        id: 142,
        state_id: 9,
        state_name: "Gracias a Dios",
        name: "Ahuas",
      },
      {
        id: 143,
        state_id: 9,
        state_name: "Gracias a Dios",
        name: "Juan Francisco Bulnes",
      },
      {
        id: 144,
        state_id: 9,
        state_name: "Gracias a Dios",
        name: "Ramón Villeda Morales",
      },
      {
        id: 145,
        state_id: 9,
        state_name: "Gracias a Dios",
        name: "Wampusirpe",
      },

      {
        id: 146,
        state_id: 10,
        state_name: "Intibucá",
        name: "La Esperanza",
      },
      {
        id: 147,
        state_id: 10,
        state_name: "Intibucá",
        name: "Camasca",
      },
      {
        id: 148,
        state_id: 10,
        state_name: "Intibucá",
        name: "Colomoncagua",
      },
      {
        id: 149,
        state_id: 10,
        state_name: "Intibucá",
        name: "Concepción",
      },
      {
        id: 150,
        state_id: 10,
        state_name: "Intibucá",
        name: "Dolores",
      },
      {
        id: 151,
        state_id: 10,
        state_name: "Intibucá",
        name: "Intibucá",
      },
      {
        id: 152,
        state_id: 10,
        state_name: "Intibucá",
        name: "Jesús de Otoro",
      },
      {
        id: 153,
        state_id: 10,
        state_name: "Intibucá",
        name: "Magdalena",
      },
      {
        id: 154,
        state_id: 10,
        state_name: "Intibucá",
        name: "Masaguara",
      },
      {
        id: 155,
        state_id: 10,
        state_name: "Intibucá",
        name: "San Antonio",
      },
      {
        id: 156,
        state_id: 10,
        state_name: "Intibucá",
        name: "San Isidro",
      },
      {
        id: 157,
        state_id: 10,
        state_name: "Intibucá",
        name: "San Juan",
      },
      {
        id: 158,
        state_id: 10,
        state_name: "Intibucá",
        name: "San Marcos de la Sierra",
      },
      {
        id: 159,
        state_id: 10,
        state_name: "Intibucá",
        name: "San Miguel Guancapla",
      },
      {
        id: 160,
        state_id: 10,
        state_name: "Intibucá",
        name: "Santa Lucía",
      },
      {
        id: 161,
        state_id: 10,
        state_name: "Intibucá",
        name: "Yamaranguila",
      },
      {
        id: 162,
        state_id: 10,
        state_name: "Intibucá",
        name: "San Francisco de Opalaca",
      },

      //ends 10
      {
        id: 163,
        state_id: 11,
        state_name: "Islas de la Bahía",
        name: "Roatán",
      },
      {
        id: 164,
        state_id: 11,
        state_name: "Islas de la Bahía",
        name: "Guanaja",
      },
      {
        id: 165,
        state_id: 11,
        state_name: "Islas de la Bahía",
        name: "José Santos Guardiola",
      },
      {
        id: 166,
        state_id: 11,
        state_name: "Islas de la Bahía",
        name: "Utila",
      },

      {
        id: 167,
        state_id: 12,
        state_name: "La Paz",
        name: "La Paz",
      },
      {
        id: 168,
        state_id: 12,
        state_name: "La Paz",
        name: "Aguanqueterique",
      },
      {
        id: 169,
        state_id: 12,
        state_name: "La Paz",
        name: "Cabañas",
      },
      {
        id: 170,
        state_id: 12,
        state_name: "La Paz",
        name: "Cane",
      },
      {
        id: 171,
        state_id: 12,
        state_name: "La Paz",
        name: "Chinacla",
      },
      {
        id: 172,
        state_id: 12,
        state_name: "La Paz",
        name: "Guajiquiro",
      },
      {
        id: 173,
        state_id: 12,
        state_name: "La Paz",
        name: "Lauterique",
      },
      {
        id: 174,
        state_id: 12,
        state_name: "La Paz",
        name: "Marcala",
      },
      {
        id: 175,
        state_id: 12,
        state_name: "La Paz",
        name: "Mercedes de Oriente",
      },
      {
        id: 176,
        state_id: 12,
        state_name: "La Paz",
        name: "Opatoro",
      },
      {
        id: 177,
        state_id: 12,
        state_name: "La Paz",
        name: "San Antonio del Norte",
      },
      {
        id: 178,
        state_id: 12,
        state_name: "La Paz",
        name: "San José",
      },
      {
        id: 179,
        state_id: 12,
        state_name: "La Paz",
        name: "San Juan",
      },
      {
        id: 180,
        state_id: 12,
        state_name: "La Paz",
        name: "San Pedro de Tutule",
      },
      {
        id: 181,
        state_id: 12,
        state_name: "La Paz",
        name: "Santa Ana",
      },
      {
        id: 182,
        state_id: 12,
        state_name: "La Paz",
        name: "Santa Elena",
      },
      {
        id: 183,
        state_id: 12,
        state_name: "La Paz",
        name: "Santa María",
      },
      {
        id: 184,
        state_id: 12,
        state_name: "La Paz",
        name: "Santiago de Puringla",
      },
      {
        id: 185,
        state_id: 12,
        state_name: "La Paz",
        name: "Yarula",
      },

      {
        id: 186,
        state_id: 13,
        state_name: "Lempira",
        name: "Gracias",
      },
      {
        id: 187,
        state_id: 13,
        state_name: "Lempira",
        name: "Belén",
      },
      {
        id: 188,
        state_id: 13,
        state_name: "Lempira",
        name: "Candelaria",
      },
      {
        id: 189,
        state_id: 13,
        state_name: "Lempira",
        name: "Cololaca",
      },
      {
        id: 190,
        state_id: 13,
        state_name: "Lempira",
        name: "Erandique",
      },
      {
        id: 191,
        state_id: 13,
        state_name: "Lempira",
        name: "Gualcince",
      },
      {
        id: 192,
        state_id: 13,
        state_name: "Lempira",
        name: "Guarita",
      },
      {
        id: 193,
        state_id: 13,
        state_name: "Lempira",
        name: "La Campa",
      },
      {
        id: 194,
        state_id: 13,
        state_name: "Lempira",
        name: "La Iguala",
      },
      {
        id: 195,
        state_id: 13,
        state_name: "Lempira",
        name: "Las Flores",
      },
      {
        id: 196,
        state_id: 13,
        state_name: "Lempira",
        name: "La Unión",
      },
      {
        id: 197,
        state_id: 13,
        state_name: "Lempira",
        name: "La Virtud",
      },
      {
        id: 198,
        state_id: 13,
        state_name: "Lempira",
        name: "Lepaera",
      },
      {
        id: 199,
        state_id: 13,
        state_name: "Lempira",
        name: "Mapulaca",
      },
      {
        id: 200,
        state_id: 13,
        state_name: "Lempira",
        name: "Piraera",
      },
      {
        id: 201,
        state_id: 13,
        state_name: "Lempira",
        name: "San Andrés",
      },
      {
        id: 202,
        state_id: 13,
        state_name: "Lempira",
        name: "San Francisco",
      },
      {
        id: 203,
        state_id: 13,
        state_name: "Lempira",
        name: "San Juan Guarita",
      },
      {
        id: 204,
        state_id: 13,
        state_name: "Lempira",
        name: "San Manuel Colohete",
      },
      {
        id: 205,
        state_id: 13,
        state_name: "Lempira",
        name: "San Rafael",
      },
      {
        id: 206,
        state_id: 13,
        state_name: "Lempira",
        name: "San Sebastián",
      },
      {
        id: 207,
        state_id: 13,
        state_name: "Lempira",
        name: "Santa Cruz",
      },
      {
        id: 208,
        state_id: 13,
        state_name: "Lempira",
        name: "Talgua",
      },
      {
        id: 209,
        state_id: 13,
        state_name: "Lempira",
        name: "Tambla",
      },
      {
        id: 210,
        state_id: 13,
        state_name: "Lempira",
        name: "Tomalá",
      },
      {
        id: 211,
        state_id: 13,
        state_name: "Lempira",
        name: "Valladolid",
      },
      {
        id: 212,
        state_id: 13,
        state_name: "Lempira",
        name: "Virginia",
      },
      {
        id: 213,
        state_id: 13,
        state_name: "Lempira",
        name: "San Marcos de Caiquín",
      },


      {
        id: 214,
        state_id: 14,
        state_name: "Ocotepeque",
        name: "Ocotepeque",
      },
      {
        id: 215,
        state_id: 14,
        state_name: "Ocotepeque",
        name: "Belén Gualcho",
      },
      {
        id: 216,
        state_id: 14,
        state_name: "Ocotepeque",
        name: "Concepción",
      },
      {
        id: 217,
        state_id: 14,
        state_name: "Ocotepeque",
        name: "Dolores Merendón",
      },
      {
        id: 218,
        state_id: 14,
        state_name: "Ocotepeque",
        name: "Fraternidad",
      },
      {
        id: 219,
        state_id: 14,
        state_name: "Ocotepeque",
        name: "La Encarnación",
      },
      {
        id: 220,
        state_id: 14,
        state_name: "Ocotepeque",
        name: "La Labor",
      },
      {
        id: 221,
        state_id: 14,
        state_name: "Ocotepeque",
        name: "Lucerna",
      },
      {
        id: 222,
        state_id: 14,
        state_name: "Ocotepeque",
        name: "Mercedes",
      },
      {
        id: 223,
        state_id: 14,
        state_name: "Ocotepeque",
        name: "San Fernando",
      },
      {
        id: 224,
        state_id: 14,
        state_name: "Ocotepeque",
        name: "San Francisco del Valle",
      },
      {
        id: 225,
        state_id: 14,
        state_name: "Ocotepeque",
        name: "San Jorge",
      },
      {
        id: 226,
        state_id: 14,
        state_name: "Ocotepeque",
        name: "San Marcos",
      },
      {
        id: 227,
        state_id: 14,
        state_name: "Ocotepeque",
        name: "Santa Fe",
      },
      {
        id: 228,
        state_id: 14,
        state_name: "Ocotepeque",
        name: "Sensenti",
      },
      {
        id: 229,
        state_id: 14,
        state_name: "Ocotepeque",
        name: "Sinuapa",
      },
      
      {
        id: 230,
        state_id: 15,
        state_name: "Olancho",
        name: "Juticalpa",
      },
      {
        id: 231,
        state_id: 15,
        state_name: "Olancho",
        name: "Campamento",
      },
      {
        id: 232,
        state_id: 15,
        state_name: "Olancho",
        name: "Catacamas",
      },
      {
        id: 233,
        state_id: 15,
        state_name: "Olancho",
        name: "Concordia",
      },
      {
        id: 234,
        state_id: 15,
        state_name: "Olancho",
        name: "Dulce Nombre de Culmí",
      },
      {
        id: 235,
        state_id: 15,
        state_name: "Olancho",
        name: "El Rosario",
      },
      {
        id: 236,
        state_id: 15,
        state_name: "Olancho",
        name: "Esquipulas del Norte",
      },
      {
        id: 237,
        state_id: 15,
        state_name: "Olancho",
        name: "Gualaco",
      },
      {
        id: 238,
        state_id: 15,
        state_name: "Olancho",
        name: "Guarizama",
      },
      {
        id: 239,
        state_id: 15,
        state_name: "Olancho",
        name: "Guata",
      },
      {
        id: 240,
        state_id: 15,
        state_name: "Olancho",
        name: "Guayape",
      },
      {
        id: 241,
        state_id: 15,
        state_name: "Olancho",
        name: "Jano",
      },
      {
        id: 242,
        state_id: 15,
        state_name: "Olancho",
        name: "La Unión",
      },
      {
        id: 243,
        state_id: 15,
        state_name: "Olancho",
        name: "Mangulile",
      },
      {
        id: 244,
        state_id: 15,
        state_name: "Olancho",
        name: "Manto",
      },
      {
        id: 245,
        state_id: 15,
        state_name: "Olancho",
        name: "Salamá",
      },
      {
        id: 246,
        state_id: 15,
        state_name: "Olancho",
        name: "San Esteban",
      },
      {
        id: 247,
        state_id: 15,
        state_name: "Olancho",
        name: "San Francisco de Becerra",
      },
      {
        id: 248,
        state_id: 15,
        state_name: "Olancho",
        name: "San Francisco de la Paz",
      },
      {
        id: 249,
        state_id: 15,
        state_name: "Olancho",
        name: "Santa María del Real",
      },
      {
        id: 250,
        state_id: 15,
        state_name: "Olancho",
        name: "Silca",
      },
      {
        id: 251,
        state_id: 15,
        state_name: "Olancho",
        name: "Yocón",
      },
      {
        id: 252,
        state_id: 15,
        state_name: "Olancho",
        name: "Patuca",
      },

      {
        id: 253,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Santa Bárbara",
      },
      {
        id: 254,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Arada",
      },
      {
        id: 255,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Atima",
      },
      {
        id: 256,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Azacualpa",
      },
      {
        id: 257,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Ceguaca",
      },
      {
        id: 258,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Concepción del Norte",
      },
      {
        id: 259,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Concepción del Sur",
      },
      {
        id: 260,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Chinda",
      },
      {
        id: 261,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "El Níspero",
      },
      {
        id: 262,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Gualala",
      },
      {
        id: 263,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Ilama",
      },
      {
        id: 264,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Las Vegas",
      },
      {
        id: 265,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Macuelizo",
      },
      {
        id: 266,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Naranjito",
      },
      {
        id: 267,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Nuevo Celilac",
      },
      {
        id: 268,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Nueva Frontera",
      },
      {
        id: 269,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Petoa",
      },
      {
        id: 270,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Protección",
      },
      {
        id: 271,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Quimistán",
      },
      {
        id: 272,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "San Francisco de Ojuera",
      },
      {
        id: 273,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "San José de las Colinas",
      },
      {
        id: 274,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "San Luis",
      },
      {
        id: 275,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "San Marcos",
      },
      {
        id: 276,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "San Nicolás",
      },
      {
        id: 277,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "San Pedro Zacapa",
      },
      {
        id: 278,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "San Vicente Centenario",
      },
      {
        id: 279,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Santa Rita",
      },
      {
        id: 280,
        state_id: 16,
        state_name: "Santa Bárbara",
        name: "Trinidad",
      },

      {
        id: 281,
        state_id: 17,
        state_name: "Valle",
        name: "Nacaome",
      },
      {
        id: 282,
        state_id: 17,
        state_name: "Valle",
        name: "Alianza",
      },
      {
        id: 283,
        state_id: 17,
        state_name: "Valle",
        name: "Amapala",
      },
      {
        id: 284,
        state_id: 17,
        state_name: "Valle",
        name: "Aramecina",
      },
      {
        id: 285,
        state_id: 17,
        state_name: "Valle",
        name: "Caridad",
      },
      {
        id: 286,
        state_id: 17,
        state_name: "Valle",
        name: "Goascorán",
      },
      {
        id: 287,
        state_id: 17,
        state_name: "Valle",
        name: "Langue",
      },
      {
        id: 288,
        state_id: 17,
        state_name: "Valle",
        name: "San Francisco de Coray",
      },
      {
        id: 289,
        state_id: 17,
        state_name: "Valle",
        name: "San Lorenzo",
      },

      {
        id: 290,
        state_id: 18,
        state_name: "Yoro",
        name: "Yoro",
      },
      {
        id: 291,
        state_id: 18,
        state_name: "Yoro",
        name: "Arenal",
      },
      {
        id: 292,
        state_id: 18,
        state_name: "Yoro",
        name: "El Negrito",
      },
      {
        id: 293,
        state_id: 18,
        state_name: "Yoro",
        name: "El Progreso",
      },
      {
        id: 294,
        state_id: 18,
        state_name: "Yoro",
        name: "Jocón",
      },
      {
        id: 295,
        state_id: 18,
        state_name: "Yoro",
        name: "Morazán",
      },
      {
        id: 296,
        state_id: 18,
        state_name: "Yoro",
        name: "Olanchito",
      },
      {
        id: 297,
        state_id: 18,
        state_name: "Yoro",
        name: "Santa Rita",
      },
      {
        id: 298,
        state_id: 18,
        state_name: "Yoro",
        name: "Sulaco",
      },
      {
        id: 299,
        state_id: 18,
        state_name: "Yoro",
        name: "Victoria",
      },
      {
        id: 300,
        state_id: 18,
        state_name: "Yoro",
        name: "Yorito",
      },
    ],
  };
  